name: Translate docs

on:
  push:
    branches:
      - release-*
      - docs-*

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenCC
        run: |
          sudo apt-get install libopencc-dev -y

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        # uses: shivammathur/setup-php@v2
        uses: shivammathur/setup-php@verbose
        with:
          php-version: 8.0
          tools: phpize
          extensions: swoole, redis, nauxliu/opencc4php
          ini-values: extension=opencc

      # - name: Build opencc4php
      #   run: |
      #     git clone https://github.com/nauxliu/opencc4php.git --depth 1
      #     cd opencc4php
      #     phpize
      #     ./configure
      #     make
      #     sudo make install
      #     php --ri opencc
      #     cd ..
      #     rm -rf opencc4php

      - name: Print Information
        run: |
          php -v
          php --ri opencc

      - name: Start Translate
        run: |
          composer install
          php bin/doc-translate

      - name: Commit Updated
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update docs and translate
