name: Split Repos

on:
  push:
  workflow_dispatch:
    inputs:
      event:
        description: 'Input your event'
        required: false
        default: ''

jobs:
  split:
    if: github.repository == 'limingxinleo/hyperf'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Split And Push
        run: |
          git config pull.rebase true
          ./bin/split-linux.sh amqp
