name: Test For Lint

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  cs-fix:
    name: PHP CS Fix on PHP${{ matrix.php }} ${{ matrix.swoole }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.1' ]
        swoole: [ 'swoole']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: php-cs-fixer
          extensions: redis, pdo, pdo_mysql, bcmath, ${{ matrix.swoole }}
      - name: Setup Packages
        run: composer update -oW
      - name: Check Composer Json
        run: |
          composer normalize --dry-run --no-update-lock
          find ./src -name composer.json -exec composer normalize --dry-run --no-update-lock {} \;
      - name: Run CS Fix
        run: vendor/bin/php-cs-fixer fix src --dry-run --diff
